DEFAULT_BUFFER_SIZE = 1048576  # 1024 * 1024
DEFAULT_APP_NAME = "audius-py"
AUDIUS_APP_NAME_ENV_VAR = "AUDIUS_APP_NAME"
AUDIUS_HOST_NAME_ENV_VAR = "AUDIUS_HOST_NAME"
AUDIUS_PLAYER_ENV_VAR = "AUDIUS_PLAYER"
